### ISSUE TITLE
how do i fix this?

### ISSUE THREAD

**Issue by JacksonTheProgrammer** [timothyliutl/discordmemebot#1]
![image](https://user-images.githubusercontent.com/87233635/137629869-82155af2-3d6e-4007-8241-a2d2e2c7e7cf.png)

**Comment by timothyliutl** [comment]
This is an issue with node syntax, I believe you must update to the latest node version

**Comment by JacksonTheProgrammer** [comment]
> an issue with node syntax, I believe you must update to the latest node version

how do i do that in repl.it ?

**Comment by timothyliutl** [comment]
Not sure about that, I'm not too familiar with repl.it 

But according to the discord.js documentation you do need node 16.6.0 or newer to use the package
https://discord.js.org/#/docs/main/stable/general/welcome
